name: DevSecOps CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  security-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install yamllint
        run: pip install yamllint

      - name: Lint Kubernetes YAML
        run: yamllint k8s/deployment.yaml

      - name: Build Docker image
        run: docker build -t flask-devsecops:latest .

      - name: Trivy filesystem scan
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          output: 'trivy-fs-report.txt'

      - name: Show Trivy filesystem results
        run: cat trivy-fs-report.txt

      - name: Trivy image scan
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          image-ref: 'flask-devsecops:latest'
          format: 'table'
          output: 'trivy-image-report.txt'

      - name: Show Trivy image results
        run: cat trivy-image-report.txt

      - name: Install Conftest
        run: |
          wget https://github.com/open-policy-agent/conftest/releases/download/v0.55.0/conftest_0.55.0_Linux_x86_64.tar.gz
          tar xzf conftest_0.55.0_Linux_x86_64.tar.gz
          sudo mv conftest /usr/local/bin/
          conftest --version

      - name: Run Conftest on Kubernetes manifest
        run: conftest test k8s/deployment.yaml --policy policy/
